"""empty message

Revision ID: 33b71fe7c62c
Revises: 
Create Date: 2024-09-27 11:52:08.080112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b71fe7c62c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stocktype', sa.Enum('monitor', 'teclado', 'cable', 'mouse', 'camara', name='stocktypeenum'), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=False),
    sa.Column('lastName', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('usertype', sa.Enum('tecnico', 'usuario', name='usertypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_uuid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('detailForm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formId', sa.Integer(), nullable=False),
    sa.Column('stockId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stocktype', sa.Enum('monitor', 'teclado', 'cable', 'mouse', 'camara', name='stocktypeenum'), nullable=False),
    sa.Column('initialDate', sa.Date(), nullable=False),
    sa.Column('finalDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['formId'], ['form.id'], ),
    sa.ForeignKeyConstraint(['stockId'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailForm')
    op.drop_table('user_uuid')
    op.drop_table('form')
    op.drop_table('user')
    op.drop_table('stock')
    # ### end Alembic commands ###
